language: node_js
sudo: false
node_js:
  - 10
  - 8
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
#  - npm i -g npm@5.7.1
scripts:
# run tests, build, ...
script:
  - npm run test:unit
