export default [
  { text : "C2"},
  { text : "C#2"},
  { text : "D2"},
  { text : "D#2"},
  { text : "E2"},
  { text : "F2"},
  { text : "F#2"},
  { text : "G2"},
  { text : "G#2"},
  { text : "A2"},
  { text : "A#2"},
  { text : "B2"},

  { text : "C3"},
  { text : "C#3"},
  { text : "D3"},
  { text : "D#3"},
  { text : "E3"},
  { text : "F3"},
  { text : "F#3"},
  { text : "G3"},
  { text : "G#3"},
  { text : "A3"},
  { text : "A#3"},
  { text : "B3"},

  { text : "C4"},
  { text : "C#4"},
  { text : "D4"},
  { text : "D#4"},
  { text : "E4"},
  { text : "F4"},
  { text : "F#4"},
  { text : "G4"},
  { text : "G#4"},
  { text : "A4"},
  { text : "A#4"},
  { text : "B4"},

  { text : "C5"},
  { text : "C#5"},
  { text : "D5"},
  { text : "D#5"},
  { text : "E5"},
  { text : "F5"},
  { text : "F#5"},
  { text : "G5"},
  { text : "G#5"},
  { text : "A5"},
  { text : "A#5"},
  { text : "B5"},
/*
  { text : "C6"},
  { text : "C#6"},
  { text : "D6"},
  { text : "D#6"},
  { text : "E6"},
  { text : "F6"},
  { text : "F#6"},
  { text : "G6"},
  { text : "G#6"},
  { text : "A6"},
  { text : "A#6"},
  { text : "B6"}*/
]