export default [
  { text : "C2", midi : 84 },
  { text : "C#2", midi : 84 },
  { text : "D2", midi : 84 },
  { text : "D#2", midi : 84 },
  { text : "E2", midi : 84 },
  { text : "F2", midi : 84 },
  { text : "F#2", midi : 84 },
  { text : "G2", midi : 84 },
  { text : "G#2", midi : 84 },
  { text : "A2", midi : 84 },
  { text : "A#2", midi : 84 },
  { text : "B2", midi : 84 },

  { text : "C3", midi : 84 },
  { text : "C#3", midi : 84 },
  { text : "D3", midi : 84 },
  { text : "D#3", midi : 84 },
  { text : "E3", midi : 84 },
  { text : "F3", midi : 84 },
  { text : "F#3", midi : 84 },
  { text : "G3", midi : 84 },
  { text : "G#3", midi : 84 },
  { text : "A3", midi : 84 },
  { text : "A#3", midi : 84 },
  { text : "B3", midi : 84 },

  { text : "C4", midi : 84 },
  { text : "C#4", midi : 84 },
  { text : "D4", midi : 84 },
  { text : "D#4", midi : 84 },
  { text : "E4", midi : 84 },
  { text : "F4", midi : 84 },
  { text : "F#4", midi : 84 },
  { text : "G4", midi : 84 },
  { text : "G#4", midi : 84 },
  { text : "A4", midi : 84 },
  { text : "A#4", midi : 84 },
  { text : "B4", midi : 84 },

  { text : "C5", midi : 84 },
  { text : "C#5", midi : 84 },
  { text : "D5", midi : 84 },
  { text : "D#5", midi : 84 },
  { text : "E5", midi : 84 },
  { text : "F5", midi : 84 },
  { text : "F#5", midi : 84 },
  { text : "G5", midi : 84 },
  { text : "G#5", midi : 84 },
  { text : "A5", midi : 84 },
  { text : "A#5", midi : 84 },
  { text : "B5", midi : 84 },

  { text : "C6", midi : 84 },
  { text : "C#6", midi : 84 },
  { text : "D6", midi : 84 },
  { text : "D#6", midi : 84 },
  { text : "E6", midi : 84 },
  { text : "F6", midi : 84 },
  { text : "F#6", midi : 84 },
  { text : "G6", midi : 84 },
  { text : "G#6", midi : 84 },
  { text : "A6", midi : 84 },
  { text : "A#6", midi : 84 },
  { text : "B6", midi : 84 }
]